services:
  postgres:
    image: postgres:16
    container_name: students-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentsdb
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: students-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/studentsdb?schema=public
      JWT_SECRET: minha_chave_super_secreta_123
    depends_on:
      - postgres